Upgrade Albert plugins to v5
11:28:12 [warn:albert.python] AttributeError: 'Constant' object has no attribute 'elts' /usr/share/albert/python/plugins/wayland-emoji -> need to convert the md_authors to a list, this is now strictly enforced (but change not documented)